hasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView

from questions import views

urlpatterns = [
    path('', views.index, name='index'),
    path('questions/', include('questions.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico")),
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.index, name='index'),
    path('hot', views.index_hot, name='hot'),
    path('search', views.index_search, name='search'),
    path('<int:question_id>', views.show_question, name='question'),
    path('add', views.make_question, name='make_question'),
    path('tag/<int:tag_id>', views.search_tag, name='searchtag'),
    path('alterflag/<int:answer_id>', views.alter_flag, name='alterflag'),
    path('answervote/<int:answer_id>/<int:vote>', views.answer_vote,
         name='answervote'),
    path('questionvote/<int:question_id>/<int:vote>', views.question_vote,
         name='questionvote')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('login', views.Login.as_view(), name='login'),
    path('signup', views.signup, name='signup')
]

questions/models.py
from django.conf import settings as sett
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models, transaction

from .helpers import get_time_diff

QUESTION_STATUS = (
    (0, 'No_answer'),
    (1, 'Answered')
)

ANSWER_STATUS = (
    (0, 'Just_answer'),
    (1, 'Right_answer')
)

VOTE_STATUS = (
    (-1, 'Downvote'),
    (0, 'No_vote'),
    (1, 'Upvote')
)


class Question(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(sett.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=QUESTION_STATUS, default=0)
    votes = models.IntegerField(default=0)

    def __str___(self):
        return self.title

    def get_answers_number(self):
        return Answer.objects.filter(question=self.id).count()

    def get_tags(self):
        return Tag.objects.filter(questions=self.id)

    @property
    def number_answers(self):
        return self.get_answers_number()

    @property
    def tags(self):
        return self.get_tags()

    @property
    def asked_ago(self):
        return get_time_diff(self.created_on)

    @classmethod
    def trending(cls):
        queryset = cls.objects.all().order_by('-votes')
        # return first X trending questions
        return queryset[:sett.TRENDING_QUESTIONS_NUMBER]


class Answer(models.Model):
    author = models.ForeignKey(sett.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    answer_flag = models.IntegerField(choices=ANSWER_STATUS, default=0)
    votes = models.IntegerField(default=0)

    @transaction.atomic
    def set_new_flag(self):
        """
        Question author marked the answer as 'best'. Set 'answer flag'
        for the answer (from 0 to 1) and set question status as 'answer
        given' (1).
        """
        qw = self.question
        self.answer_flag = 1
        qw.status = 1
        qw.save()
        self.save()

    @transaction.atomic
    def change_flag(self):
        """
        Question author changed his/her mind and marked another answer
        as best. Set 'answer flag' for the answer (from 0 to 1) and set
        question status as 'answer given' (1).
        """
        qw = self.question
        prev_answer = qw.answer_set.get(answer_flag=1)
        prev_answer.answer_flag = 0
        self.answer_flag = 1
        prev_answer.save()
        self.save()

    @transaction.atomic
    def delete_flag(self):
        """
        Question author decided to unlabel the answer as 'best answer'.
        Delete 'answer flag' for the answer (set 0) and change question
        status from 'answer given' (1) to 'no answer' (0).
        """
        qw = self.question
        self.answer_flag = 0
        qw.status = 0
        self.save()
        qw.save()


class Tag(models.Model):
    title = models.CharField(max_length=15, unique=True)
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.title


class Voters(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    vote = models.IntegerField(choices=VOTE_STATUS, default=0)
    user_id = models.PositiveIntegerField()

    @staticmethod
    @transaction.atomic
    def register_vote(object: Question or Answer,
                      user_id: int, vote: int):
        """
        User votes for a question or for an answer.
        * object: instance of Question or Answer model classes
        * user_id: request.user.id
        * vote: 1 or 0 (if user upvoted or downvoted)
        """
        object_ct = ContentType.objects.get_for_model(object)
        any_voters = Voters.objects.filter(
            content_type=object_ct,
            object_id=object.id,
            user_id=user_id).count()

        if not any_voters:
            # creating new Voters record
            user_vote = Voters(content_object=object,
                               user_id=user_id)
        else:
            # fetch existing Voters record
            user_vote = Voters.objects.get(
                content_type=object_ct,
                object_id=object.id,
                user_id=user_id)

        user_upvoted = bool(vote)
        if user_upvoted:
            if user_vote.vote in (0, -1):
                # user can upvote only if he never voted
                # or if he has downvoted earlier
                object.votes += 1
                user_vote.vote += 1
                user_vote.save()
            else:
                return False
        else:
            if user_vote.vote in (0, 1):
                # user can downvote only if he never voted
                # or if he has upvoted earlier
                object.votes -= 1
                user_vote.vote -= 1
                user_vote.save()
            else:
                return False

        object.save()  # saving new votes rate for a question or for an answer
        return True

questions/forms.py
from django import forms

from .models import Question, Answer


class AnswerForm(forms.Form):
    content = forms.CharField(max_length=10000, required=True,
                              widget=forms.Textarea,
                              help_text='Try to be clear and polite')

    def __init__(self, *args, **kwargs):
        self.question_id = kwargs.pop('question_id', None)
        super(AnswerForm, self).__init__(*args, **kwargs)

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if Answer.objects.filter(question=self.question_id,
                                 content=content).count():
            raise forms.ValidationError(
                u'There is an answer with exactly the same text'
                u' for this question!'
            )
        return content


class QuestionForm(forms.Form):
    title = forms.CharField(max_length=60, required=True,
                            help_text='Nice title should be informative')
    content = forms.CharField(max_length=10000, required=True,
                              widget=forms.Textarea,
                              help_text='Short questions make good answers')
    tags = forms.CharField(max_length=60, required=False)

    def clean_tags(self):
        provided_tags = self.cleaned_data.get('tags')
        if not provided_tags:
            return []
        tags = provided_tags.split()
        if len(tags) > 3:
            raise forms.ValidationError(
                'You can only provide up to 3 tags'
            )
        return tags

    def clean_title(self):
        provided_title = self.cleaned_data.get('title')
        if Question.objects.filter(title=provided_title).count():
            raise forms.ValidationError(
                u'A question with this title already exists'
            )
        return provided_title

questions/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from hasker.signals import question_answered
from .forms import AnswerForm, QuestionForm
from .helpers import save_tags
from .models import Answer, Question, Tag, Voters

num_pages = settings.ELEMENTS_PER_PAGE  # pagination constant


def index(request, pages=num_pages):
    queryset = Question.objects.all().order_by('-created_on', 'title')
    paginator = Paginator(queryset, pages)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'questions/index.html', context)


def index_hot(request, pages=num_pages):
    queryset = Question.objects.all().order_by('-votes', 'title')
    paginator = Paginator(queryset, pages)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'questions/hot_questions.html', context)


def search_tag(request, tag_id, pages=num_pages):
    tag = Tag.objects.get(id=tag_id)
    queryset = tag.questions.all()
    paginator = Paginator(queryset, pages)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'tag': tag
    }
    return render(request, 'questions/tag.html', context)


def index_search(request, pages=num_pages):
    """
    Search question by search phrase or by tag
    """
    search: str = request.POST.get('search', None)
    if search.startswith('tag:'):
        tag_name = search[4:].strip()
        try:
            tag = Tag.objects.get(title=tag_name)
        except Tag.DoesNotExist:
            context = {'error_message': f'No tag {tag_name} found'}
            return render(request, 'questions/search.html', context)
        return search_tag(request, tag_id=tag.id)

    queryset = Question.objects.select_related().filter(
            Q(title__icontains=search)
          | Q(content__icontains=search)                        # noqa E131
          | Q(answer__content__icontains=search)                # noqa E131
        ).distinct().order_by('-votes', '-created_on')
    paginator = Paginator(queryset, pages)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'searchstring': search
    }
    return render(request, 'questions/search.html', context)


def show_question(request, question_id):
    """
    Show question page or post a new answer for a question
    """
    qw = get_object_or_404(Question, pk=question_id)
    context = {'question': qw}
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('users:login')
        form = AnswerForm(request.POST, question_id=question_id)
        if form.is_valid():
            content = form.cleaned_data.get('content')
            answer = Answer(author=request.user, question=qw,
                            content=content)
            answer.save()
            # send a signal about new answer
            question_answered.send(sender=show_question, question=qw)
    else:
        form = AnswerForm()

    answer_query = Answer.objects.filter(question=question_id).order_by(
        '-votes', '-answer_flag', '-created_on')
    tags = Tag.objects.filter(questions=question_id)
    context.update({'answer_query': answer_query, 'tags': tags, 'form': form})
    return render(request, 'questions/question.html', context)


@login_required
def make_question(request):
    """
    Post a new question to Hasker
    """
    context = {}
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            tags = form.cleaned_data.get('tags')
            question = Question(
                author=request.user,
                title=title,
                content=content
            )
            question.save()
            save_tags(tags, question, Tag)
            return redirect('questions:question', question_id=question.id)
    else:
        form = QuestionForm()
    context['form'] = form
    return render(request, 'questions/make_question.html', context)


@login_required
def alter_flag(request, answer_id):
    """
    Question author marks an answer to his question as 'best'
    or changes this choice (answer.answer_flag model field)
    """
    answer = Answer.objects.get(pk=answer_id)
    qw = answer.question

    if not qw.author.id == request.user.id:
        # only question author could mark answer as 'best'
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    if qw.author.id == answer.author.id:
        # question author cannot mark his own answers as 'best'
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    if answer.answer_flag == 1:      # this very answer is the 'best' already
        answer.delete_flag()
    else:
        if qw.status == 0:           # question has no 'best answer'
            answer.set_new_flag()
        elif qw.status == 1:         # question has another 'best answer'
            answer.change_flag()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def answer_vote(request, answer_id, vote=1):
    """
    Upvote or downvote an answer
    """
    answer = Answer.objects.get(pk=answer_id)
    if answer.author.id == request.user.id:
        # user cannot vote for his own answers
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    Voters.register_vote(object=answer, user_id=request.user.id,
                         vote=vote)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def question_vote(request, question_id, vote=1):
    """
    Upvote or downvote a question
    """
    qw = Question.objects.get(pk=question_id)
    if qw.author.id == request.user.id:
        # user cannot vote for his own questions
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    Voters.register_vote(object=qw, user_id=request.user.id,
                         vote=vote)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

questions/templates/questions/base_index.html
{% extends "base.html" %}

{% block title %}<title>Hasker - index</title>{% endblock %}

{% block content %}
{% load static %}

{% block qw_navigate %}
{% endblock %}


{% if page_obj %}

    {% for question in page_obj %}
        
          <div class="card border-light mb-3" style="max-width: 60rem; margin-top:5px; margin-bottom:5px;">

            <div class="card-header">
              <div class="text-muted">id #{{ question.id }}
              {% if question.status == 1 %}
              <img src="{% static 'questions/accept.png' %}" alt="Answered" width="20" height="20">
              {% else %}
              <img src="{% static 'questions/question.png' %}" alt="No answer yet" width="20" height="20">
              {% endif %}
              </div>
            </div>

            <div class="card-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-1">
                    <div class="row">{{ question.votes }}</div>
                    <div class="row">Votes</div>
                  </div>
                  <div class="col-1">
                    <div class="row">{{ question.number_answers }}</div>
                    <div class="row">Answers</div>
                  </div>
                  <div class="col-7" style="margin-left: 10px;">
                    <a href="{% url 'questions:question' question.id %}" class="card-block stretched-link text-decoration-none" style="text-decoration: none;">
                    <h5 class="card-title">
                      {{ question.title }}
                    </h5>
                    </a>
                    <p class="card-text">
                      {% for tag in question.tags %}
                      <a href="{% url 'questions:searchtag' tag.id %}" class="badge badge-info text-wrap">{{ tag.title }}</a>
                      {% endfor %}
                    </p>
                  </div>
                  <div class="col-2" style="margin-left: 5px;">
                    <div class="row">
                      <p><a href="#" class="text-primary">{{ question.author }}</a></p>
                    </div>
                    <div class="row">
                      <p class="text-secondary">{{ question.asked_ago }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

    {% endfor %}

    <!-- PAGE NAVIGATION -->

    <nav aria-label="Page navigation">
      <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
              </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">
                  {{ i }}
                  <span class="sr-only">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
                </span>
              </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
              </li>
            {% endif %}
      </ul>
    </nav>

    {% else %}
    <div class="card border-light mb-3" style="max-width: 60rem; margin-top:20px; margin-bottom:5px; margin-left:20px;">
        <h4>No questions are available.</h4>
    </div>
    {% endif %}


{% endblock %}

questions/templates/questions/hot_questions.html
{% extends "questions/base_index.html" %}

{% block title %}<title>Hasker - hot</title>{% endblock %}

{% block qw_navigate %}
<div class="container-fluid">
  <ul class="nav nav-tabs card-header-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'questions:index' %}">New questions</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#">Hot questions</a>
    </li>
  </ul>
</div>
{% endblock %}

questions/templates/questions/index.html
{% extends "questions/base_index.html" %}

{% block title %}<title>Hasker - main</title>{% endblock %}

{% block qw_navigate %}
<div class="container-fluid">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="#">New questions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questions:hot' %}">Hot questions</a>
      </li>
    </ul>
</div>
{% endblock %}

questions/templates/questions/make_question.html
{% extends "base.html" %}

{% block title %}<title>Hasker: ask</title>{% endblock %}

{% block content %}
{% load static %}

<form action="{% url 'questions:make_question' %}" method="post" style="margin-bottom:40px; margin-top:40px; margin-left:15px; margin-right:25px;">
  <legend><h2 style="margin-bottom:20px;">Ask your question</h2></legend>
  
  {% csrf_token %}
  {% if error_message %}
  <div class="alert alert-warning" role="alert">
      {{ error_message }}
  </div>
  {% endif %}
  {% for field in form %}
  <div class="mb-3" style="margin-bottom:40px;">
    <label for="{{ field.html_name }}" class="form-label">{{ field.label }}</label>
    {% if field.field.widget.input_type %}
    <input class="form-control form-control-sm" type="{{ field.field.widget.input_type }}" id="{{ field.id_for_label }}" name="{{ field.html_name }}">
    {% else %}
    <textarea class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" rows="6" placeholder="Your answer"></textarea>
    {% endif %}
    {% if field.help_text %}
      <small style="color: grey">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
    <div class="alert alert-warning" role="alert">
        {{ error }}
    </div>
    {% endfor %}
  </div>
  {% endfor %}
  <input type="submit" class="btn btn-primary" value="Submit"></input>
  <input type="reset" class="btn btn-secondary" value="Clear"></input>
</form>

{% endblock %}

questions/templates/questions/question.html
{% extends "base.html" %}

{% block title %}<title>Hasker: {{ question.title }}</title>{% endblock %}

{% block content %}
{% load static %}

<div class="card border-light mb-3" style="max-width: 60rem; margin-top:5px; margin-bottom:80px;">
  <div class="card-header">
    <h4>{{ question.title }}</h4>
    <h8><i>Created: {{ question.created_on }}</i></h8>
  </div>
  <div class="card-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          <div class="row">
            <a href="{% url 'questions:questionvote' question.id 1 %}">
              <img src="{% static 'questions/up_arrow.png' %}" alt="Upvote" width="40" height="40">
            </a>
          </div>
          <div class="row">
            <div class="col-1">
              <h5 class="text-align:center">{{ question.votes }}</h5>
            </div>
          </div>
          <div class="row">
            <a href="{% url 'questions:questionvote' question.id 0 %}">
              <img src="{% static 'questions/down_arrow.png' %}" alt="Downvote" width="40" height="40">
            </a>
          </div>
        </div>
        <div class="col-10">
          <div class="row">
            <p>{{ question.content }}</p>
          </div>
          <div class="row">
            <div class="col-7">
              <!-- TAGS -->
              <p class="card-text">
                {% for tag in question.tags %}
                <a href="{% url 'questions:searchtag' tag.id %}" class="badge badge-info text-wrap">{{ tag.title }}</a>
                {% endfor %}
              </p>
            </div>
            <div class="col-3">
              <!-- AUTHOR -->
              {% if question.author.profile.avatar %}
              <!-- USER AVATAR -->
              <img src="{{ question.author.profile.avatar }}" class="rounded-circle" alt="User avatar" width="50" height="50" style="margin-bottom:15px;">
              {% else %}
              <img src="{% static 'users/userpic.png' %}" alt="Default avatar" width="50" height="50" style="margin-bottom:15px;">
              {% endif %}
              <p><a href="#" class="text-primary">{{ question.author }}</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<h4 style="margin-left:10px;">Answers</h4>

{% if answer_query %}

{% for answer in answer_query %}

<div class="card border-light mb-3" style="max-width: 60rem; margin-top:5px; margin-bottom:80px;">
  <div class="card-header"></div>
  <div class="card-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          <div class="row">
            <!-- ANSWER VOTING-->
            <a href="{% url 'questions:answervote' answer.id 1 %}">
              <img src="{% static 'questions/up_arrow.png' %}" alt="Upvote" width="40" height="40">
            </a>
          </div>
          <div class="row">
            <div class="col-1">
              <h5 class="text-align:center">{{ answer.votes }}</h5>
            </div>
          </div>
          <div class="row">
            <a href="{% url 'questions:answervote' answer.id 0 %}">
              <img src="{% static 'questions/down_arrow.png' %}" alt="Downvote" width="40" height="40">
            </a>
          </div>
          <div class="row" style="margin-top:10px">
            <div class="col-1"></div>
            <div class="col-12">
              <!-- BEST ANSWER LOGIC-->
              {% if answer.answer_flag == 1 %}
              <a href="{% url 'questions:alterflag' answer.id %}"><img src="{% static 'questions/star.png' %}" alt="Best answer" width="20" height="20"></a>
              {% else %}
              <a href="{% url 'questions:alterflag' answer.id %}"><img src="{% static 'questions/emptystar.png' %}" alt="Ordinary answer" width="20" height="20"></a>
              {% endif %}
            </div>
            <div class="col-1"></div>
          </div>
        </div>
        <div class="col-10">
          <div class="row">
            <!-- ANSWER CONTENT -->
            <p>{{ answer.content }}</p>
          </div>
          <div class="row">
            <div class="col-7">
              <p class="text-secondary">Created: {{ answer.created_on }}</p>
            </div>
            <div class="col-3">
              <!-- ANSWER AUTHOR -->
              <p><a href="#" class="text-primary">{{ answer.author }}</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endfor %}
    </ul>
{% else %}
    <p>No answers for that question yet. Write one?..</p>
{% endif %}

<hr>
<!-- ANSWER FORM -->
{% if user.is_authenticated %}
<legend><h3>Your answer:</h3></legend>
<form action="{% url 'questions:question' question.id %}" method="post" style="margin-bottom:40px;">
  {% csrf_token %}
  {% if error_message %}
  <div class="alert alert-warning" role="alert">
      {{ error_message }}
  </div>
  {% endif %}

  {% for field in form %}
  <div class="mb-3" style="margin-bottom:40px;">
    <label for="{{ field.html_name }}" class="form-label">{{ field.label }}</label>
    {% if field.field.widget.input_type %}
    <p><textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" cols="70" rows="5" placeholder="Your answer"></textarea></p>
    {% else %}
    <textarea class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" rows="6" placeholder="Your question"></textarea>
    {% endif %}
    {% if field.help_text %}
      <small style="color: grey">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
    <div class="alert alert-warning" role="alert">
        {{ error }}
    </div>
    {% endfor %}
  </div>
  {% endfor %}
  <input type="submit" class="btn btn-primary" value="Submit">
  <input type="reset" class="btn btn-secondary" value="Clear">
</form>
{% else %}
<h4 style="margin-left:10px;">Please register or sign up to write an answer</h4>
{% endif %}
{% endblock %}

questions/templates/questions/search.html
{% extends "questions/base_index.html" %}

{% block title %}<title>Hasker - search</title>{% endblock %}

{% block qw_navigate %}
<div class="container-fluid">
    <h3 style="margin-top:30px; margin-bottom:30px;">Search results for "{{ searchstring }}"</h3>
  </div>
{% endblock %}

questions/templates/questions/tag.html
{% extends "questions/base_index.html" %}

{% block title %}<title>Hasker - tagsearch {{ tag }}</title>{% endblock %}

{% block qw_navigate %}
<div class="container-fluid">
  <h3 style="margin-top:30px; margin-bottom:30px;">Questions with "{{ tag }}" tag</h3>
</div>
{% endblock %}