hasker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView

from questions import views

urlpatterns = [
    path('', views.index, name='index'),
    path('questions/', include('questions.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico")),
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.index, name='index'),
    path('hot', views.index_hot, name='hot'),
    path('search', views.index_search, name='search'),
    path('<int:question_id>', views.show_question, name='question'),
    path('add', views.make_question, name='make_question'),
    path('tag/<int:tag_id>', views.search_tag, name='searchtag'),
    path('alterflag/<int:answer_id>', views.alter_flag, name='alterflag'),
    path('answervote/<int:answer_id>/<int:vote>', views.answer_vote,
         name='answervote'),
    path('questionvote/<int:question_id>/<int:vote>', views.question_vote,
         name='questionvote')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('login', views.Login.as_view(), name='login'),
    path('signup', views.signup, name='signup')
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- TITLE -->
    {% block title %}<title>Hasker - questions</title>{% endblock %}
    {% load static %}

</head>
<body style="position: relative; min-height: 100%;">
    <div class="container-fluid" style="max-width:80%;">
        <div class="container-fluid">
            <nav class="navbar navbar-dark bg-dark py-1">
                <!-- Navbar content -->
                <a class="navbar-brand" href="{% url 'questions:index' %}">
                    <img src="{% static 'img/layers.png' %}" width="25" height="25" class="d-inline-block align-top" alt="">
                    HASKER
                </a>
                <span class="navbar-text">
                    Poor-man stackoverflow
                </span>
                <form class="form-inline" action="{% url 'questions:search' %}" method="post">
                    {% csrf_token %}
                    <!-- Search -->
                    <input class="form-control form-control-sm mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-sm btn-outline-secondary btn-sm mr-sm-2" type="submit">Search</button>
                </form>
                {% if user.id %}
                <form class="form-inline">
                    {% if user.profile.avatar %}
                    <!-- USER AVATAR -->
                    <img src="{{ user.profile.avatar }}" class="rounded-circle" alt="User avatar" width="70" height="70" style="margin-right:15px;">
                    {% else %}
                    <img src="{% static 'users/userpic.png' %}" alt="Default avatar" width="70" height="70" style="margin-right:15px;">
                    {% endif %}
                    <!-- Profile link -->
                    <div class="col">
                    <div class="row">
                        <p><a href="{% url 'users:profile' %}" class="text-success" style="margin-right:15px;">{{ user.username }}</a></p>
                    </div>
                    <div class="row">
                    <!-- Exit link -->
                        <div style="margin-right:30px; margin-bottom: 5px;">
                            <a href="{% url 'users:logout' %}"><img src="{% static 'users/exit.png' %}" alt="Exit sign" width="25" height="25"></a>
                        </div>
                    </div>
                </form>
                {% else %}
                <form class="form-inline">    
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 mr-sm-3">
                        <li class="nav-item">
                          <!-- Log-in -->
                          <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                      </ul>
                    <!-- Sign up -->
                    <a class="btn btn-outline-success my-2 btn-sm mr-sm-2" type="button" href="{% url 'users:signup' %}">Sign up</a>
                </form>
                {% endif %}
            </nav>
        </div>

        <div class="container-fluid" style="margin-top: 10px; min-height:100%; position:relative; margin-bottom: 40px">
            <div class="row">
                <div class="col-8">
                    <!-- CONTENT -->
                    {% block content %}{% endblock %}
                    <!-- END CONTENT -->
                </div>
                <div class="col-3">
                    <form class="form-inline" style="margin-top: 20px;">
                        <!-- Ask button -->
                        <a class="btn btn-outline-success btn-block" type="button" href="{% url 'questions:make_question' %}">Ask!</a>
                    </form>
                
                    <div class="container-fluid" style="margin-top: 50px;">
                        <div class="row">
                            <div class="col-12" style="margin-bottom: 10px;">
                                <h4 class="text-center">Trending</h>
                            </div>
                        </div>
                        <div class="row">
                            <!-- TRENDING section -->
                            {% if trending %}
                            {% for trend in trending %}
                            <div class="col-4">
                                <button type="button" class="btn btn-primary btn-sm text-wrap" disabled>{{ trend.votes }}</button>
                            </div>
                            <div class="col-8">
                                <p><a href="{% url 'questions:question' trend.id %}" class="text-primary">{{ trend.title }}</a></p>
                            </div>
                            {% endfor %}
                            {% else %}
                            <div class="col-4">
                                <button type="button" class="btn btn-primary btn-sm text-wrap" disabled>100</button>
                            </div>
                            <div class="col-8">
                                <p><a href="#" class="text-primary">How to OTUS?</a></p>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="navbar-fixed-bottom row-fluid">
        <div class="container-fluid" style="max-width:80%; height: 25px;">
            <div class="container-fluid">
                <nav class="navbar navbar-dark bg-dark">
                    <span class="navbar-text">
                        (c) Alex Kurilov, 2022
                    </span>
                </nav>
            </div>
        </div>
    </div>
</body>
</html>